### PR TITLE
Allow optionally ignoring transient smtp errors

### PR DESCRIPTION
**Pull request by cguardia**
Raising an exception triggers alarms in some monitoring systems, even when the message is usually delivered later. Having the option of not raising exceptions in these cases can prevent this.

### CODE REVIEW

**Comment by cguardia** [comment]
@tseaver done with the requested changes, but there seems to be a conflict.

**Comment by tseaver** [comment]
@cguardia Thanks!  I've rebased your branch, squashing and fixing the conflicts.

**Comment by tseaver** [comment]
@cguardia  [released](https://pypi.python.org/pypi/repoze.sendmail/4.3)

**Comment by cguardia** [comment]
Thank you!

**Pull request closed without merging**
