### PR TITLE
Reset 'tpc_phase' to zero during 'tpc_abort' / 'tpc_finish'.

### LINKED ISSUE #31: MailDataManager breaks the transaction manager upon abort
I have some code sending emails and for legitimate reasons the email is rejected by the remote server. I want to log the exception but instead I see the `ValueError('TPC in progress')` a couple times in the output, squashing the error.

It's actually causing the transaction manager to be in such a broken state that the next transaction.manager.begin() after the failed abort, causes another exception. Below is the crap fix to prove the diagnosis, but I'm not positive it's the correct fix. I downgraded to 4.1 and things work as expected.

From what I can tell this behavior appeared in https://github.com/repoze/repoze.sendmail/commit/06ad882dc4f4a220fba2583e67076e9f3dcf3359 when the manager was rewritten.

On a related side note, aborting in the second phase of a two-phase commit is a Really Bad Thing(tm). Since sending email isn't transactional it almost makes more sense to either send the email in an earlier phase or even as an `afterCommitHook`.

``` diff
diff --git a/repoze/sendmail/delivery.py b/repoze/sendmail/delivery.py
index 59115d7..6b56add 100644
--- a/repoze/sendmail/delivery.py
+++ b/repoze/sendmail/delivery.py
@@ -115,8 +115,8 @@ class MailDataManager(object):
             raise ValueError("Not in a transaction")
         if self.transaction is not trans:
             raise ValueError("In a different transaction")
-        if self.tpc_phase != 0:
-            raise ValueError("TPC in progress")
+        #if self.tpc_phase != 0:
+        #    raise ValueError("TPC in progress")
         if self.onAbort:
             self.onAbort()
```

### PR DESCRIPTION
**Pull request by tseaver**
Closes #31.

/cc @mmerickel

### CODE REVIEW

**Comment by mmerickel** [comment]
I'll try in the next half hour here to see if I can reproduce the old error and then upgrade to see if this patch fixes it. Thanks.

**Comment by mmerickel** [comment]
I can confirm this fix appears to be working for me.

**Comment by papachoco** [comment]
Thank a lot

**Comment by mmerickel** [comment]
Is this going to get released soon?

**Comment by tseaver** [comment]
I was looking at other open PRs:  I asked for changes on #37, which is straightforward to apply.  The others (#25, #26, #34, #35) take more cycles than I have available today.

**Comment by tseaver** [comment]
@mmerickel [released](https://pypi.python.org/pypi/repoze.sendmail/4.3)

**Pull request merged**
